wireplumber.settings = {
  bluetooth.autoswitch-to-headset-profile = false
  bluetooth.use-persistent-storage = false
  device.restore-profile = false
  linking.follow-default-target = true
  node.restore-default-targets = false
}

monitor.bluez.properties = {
  bluez5.roles = [ hfp_hf hfp_ag ]
  bluez5.enable-msbc = true
  bluez5.hfphsp-backend = "native"
}

monitor.bluez.rules = [
  {
    matches = [
      { device.name = "~bluez_card.*" }
    ]
    actions = {
      update-props = {
        bluez5.auto-connect = [ hfp_hf hfp_ag ]
      }
    }
  }
  {
    matches = [
      { node.name = "~bluez_output.*" }
      { node.name = "~bluez_input.*" }
    ]
    actions = {
      update-props = {
        priority.session = 2500
      }
    }
  }
]
