wireplumber.settings = {
  bluetooth.autoswitch-to-headset-profile = true
  bluetooth.use-persistent-storage = true
  bluetooth.profile-preference = "quality"
  device.restore-profile = false
  linking.follow-default-target = true
  node.restore-default-targets = true
}

monitor.bluez.properties = {
  bluez5.roles = [ a2dp_sink a2dp_source bap_sink bap_source hfp_hf hfp_ag ]
  bluez5.enable-msbc = true
  bluez5.enable-sbc-xq = true
  bluez5.hfphsp-backend = "native"
}

monitor.bluez.rules = [
  {
    matches = [
      { device.name = "~bluez_card.*" }
    ]
    actions = {
      update-props = {
        device.profile = "a2dp-sink"
        bluez5.auto-connect = [ a2dp_sink hfp_hf hfp_ag ]
      }
    }
  }
  {
    matches = [
      { node.name = "~bluez_output.*" }
    ]
    actions = {
      update-props = {
        priority.session = 1200
      }
    }
  }
]
