wireplumber.components = [
  {
    name = /home/amos/.config/wireplumber/scripts/freeclip-session.lua
    type = script/lua
    provides = custom.freeclip-session
    requires = [ metadata.default, monitor.bluez, support.standard-event-source ]
  }
]

wireplumber.profiles = {
  main = {
    custom.freeclip-session = required
  }
}
