wireplumber.components = [
  {
    name = /home/amos/.config/wireplumber/scripts/freeclip-routing.lua
    type = script/lua
    provides = custom.freeclip-routing
    requires = [ metadata.default ]
  }
]

wireplumber.profiles = {
  main = {
    custom.freeclip-routing = required
  }
}
