# Trigger Mode
TriggerMode=Hold
# Command Keys
CommandKeys=
# Command Palette Keys
MenuKey=
# Previous Page Keys
PagePrevKeys=
# Next Page Keys
PageNextKeys=
# Max Streaming Display Width
MaxStreamingDisplayWidth=60

[TriggerKey]
0=Insert

