;; -*- no-byte-compile: t; -*-

(package! centered-window-mode :disable t)
(package! evil-matchit :disable t)
(package! evil-numbers :disable t)
(package! git-gutter-fringe :disable t)
(package! magit-todos :disable t)
(package! smerge-mode :disable t)
(package! solaire-mode :disable t)
(package! stripe-buffer :disable t)
(package! vi-tilde-fringe :disable t)
(package! visual-fill-column :disable t)

(package! adoc-mode)
(package! bind-map)
(package! chinese-yasdcv)
(package! company-lsp)
(package! counsel-dash)
(package! cquery)
(package! dired-quick-sort)
(package! easy-hugo)
(package! evil-magit)
(package! fcitx)
(package! fish-mode)
(package! general)
(package! git-gutter)
(package! git-timemachine)
(package! gitattributes-mode)
(package! gitconfig-mode)
(package! gitignore-mode)
(package! go-playground)
(package! helm-make)
(package! kurecolor)
(package! link-hint)
(package! lispyville)
(package! lsp-mode)
(package! lsp-ui)
(package! magit-svn)
(package! move-text)
(package! narrow-reindent)
(package! ov)
(package! page-break-lines)
(package! pdf-tools)
(package! rust-playground)
(package! sdcv)
(package! syntactic-close)
(package! unfill)
(package! ws-butler)
(package! yapfify)

(package! cc-playground :recipe (:fetcher github :repo "amosbird/cc-playground" :files ("*.el" "templates")))
(package! color-moccur :recipe (:fetcher github :repo "myuhe/color-moccur.el"))
(package! moccur-edit :recipe (:fetcher github :repo "myuhe/moccur-edit.el"))
(package! dired-hacks :recipe (:fetcher github :repo "Fuco1/dired-hacks"))
(package! dired-k :recipe (:fetcher github :repo "amosbird/emacs-dired-k"))
(package! direnv :recipe (:fetcher github :repo "wbolster/emacs-direnv"))
(package! evil-terminal-cursor-changer :recipe (:fetcher github :repo "amosbird/evil-terminal-cursor-changer"))
(package! evil-textobj-line :recipe (:fetcher github :repo "syohex/evil-textobj-line"))
(package! font-lock+ :recipe (:fetcher github :repo "emacsmirror/font-lock-plus"))
(package! google-translate :recipe (:fetcher github :repo "atykhonov/google-translate"))
(package! help-fns+ :recipe (:fetcher github :repo "emacsmirror/help-fns-plus"))
(package! hl-line+ :recipe (:fetcher github :repo "emacsmirror/hl-line-plus"))
(package! ivy-rich :recipe (:fetcher github :repo "Yevgnen/ivy-rich"))
(package! osc :recipe (:fetcher github :repo "amosbird/osc.el"))
(package! rainbow-mode :recipe (:fetcher github :repo "amosbird/rainbow-mode"))
(package! realign-mode :recipe (:fetcher github :repo "amosbird/realign-mode.el"))
