# vim:fileencoding=utf-8:foldmethod=marker

# Appearance {{{

# System color scheme (dark/light/no-preference)
color_scheme no-preference

# System accent color
accent_color cyan

# Preferred contrast level
contrast normal

file_chooser_size 35 120

# }}}
