context.modules = [
  {
    name = libpipewire-module-loopback
    args = {
      node.description = "FreeClip Stable Output"
      audio.position = [ FL FR ]
      capture.props = {
        node.name = "freeclip_stable_output"
        node.description = "FreeClip Stable Output"
        media.class = Audio/Sink
        node.virtual = false
        state.restore-props = false
      }
      playback.props = {
        node.name = "freeclip_stable_output.backend"
        node.description = "FreeClip Stable Output Backend"
        target.object = "bluez_output.C0_DA_5E_EC_FB_7F.1"
        node.passive = true
        node.dont-fallback = true
        node.linger = true
        state.restore-props = false
      }
    }
  }
  {
    name = libpipewire-module-loopback
    args = {
      node.description = "FreeClip Stable Input"
      audio.channels = 1
      audio.position = [ MONO ]
      capture.props = {
        node.name = "freeclip_stable_input.backend"
        node.description = "FreeClip Stable Input Backend"
        target.object = "bluez_input.C0:DA:5E:EC:FB:7F"
        node.passive = true
        node.dont-fallback = true
        node.linger = true
        state.restore-props = false
      }
      playback.props = {
        node.name = "freeclip_stable_input"
        node.description = "FreeClip Stable Input"
        media.class = Audio/Source
        node.virtual = false
        state.restore-props = false
      }
    }
  }
]
