# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Aliases for commands. The keys of the given dictionary are the
# aliases, while the values are the commands they map to.
# Type: Dict
c.aliases = {'q': 'quit', 'w': 'session-save', 'wq': 'quit --save'}

# List of domains that should always be loaded, despite being ad-
# blocked. Domains may contain * and ? wildcards and are otherwise
# required to exactly match the requested domain. Local domains are
# always exempt from hostblocking.
# Type: List of String
c.content.host_blocking.whitelist = ['piwik.org', 'avgle.com']

# How to behave when the last tab is closed.
# Type: String
# Valid values:
#   - ignore: Don't do anything.
#   - blank: Load a blank page.
#   - startpage: Load the start page.
#   - default-page: Load the default page.
#   - close: Close the window.
c.tabs.last_close = 'close'

# Bindings for normal mode
config.bind('<Ctrl-Space>', 'spawn i3-msg focus right')
config.bind('<Ctrl-b>', 'navigate prev')
config.bind('<Ctrl-f>', 'navigate next')
config.bind('<Ctrl-i>', 'forward')
config.bind('<Ctrl-o>', 'back')
config.bind('<Ctrl-r>', 'undo')
config.bind('I', 'tab-close')
config.bind('O', 'set-cmd-text :open {url:pretty}')
config.bind('T', 'set-cmd-text :open -t -r {url:pretty}')
config.bind('d', 'scroll-page 0 0.5')
config.bind('p', 'open -t -- {clipboard}')
config.bind('t', 'set-cmd-text -s :open -t')
config.bind('u', 'scroll-page 0 -0.5')

# Bindings for command mode
config.bind('<Ctrl-D>', 'rl-delete-char', mode='command')
config.bind('<Ctrl-J>', 'completion-item-focus next', mode='command')
config.bind('<Ctrl-K>', 'completion-item-focus prev', mode='command')
config.bind('<Ctrl-O>', 'rl-kill-line', mode='command')

# Bindings for prompt mode
config.bind('<Ctrl-D>', 'rl-delete-char', mode='prompt')
config.bind('<Ctrl-J>', 'prompt-item-focus next', mode='prompt')
config.bind('<Ctrl-K>', 'prompt-item-focus prev', mode='prompt')
config.bind('<Ctrl-O>', 'rl-kill-line', mode='prompt')
