Section "InputClass"
    Identifier "touchpad"
    Driver "libinput"
    MatchIsTouchpad "on"
    Option "Tapping" "on"
    Option "TappingDrag" "on"
    Option "TappingDragLock" "off"
    Option "TappingButtonMap" "lrm"
    Option "DisableWhileTyping" "on"
    Option "AccelSpeed" "0.8"
EndSection
