#!/usr/bin/env fish

# if test -e "$BSPWM_STATE"
# 	bspc wm -l "$BSPWM_STATE"
# 	rm "$BSPWM_STATE"
# end

bspc monitor -d w e d f v n i o c h
if [ (hostname) = "abt480" ]
    bspc monitor DP2 -r
else
    bspc monitor DP2-2 -r
end

bspc config border_width         0
bspc config window_gap           0
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config swallow_first_click  true
bspc config gapless_monocle      false
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config pointer_modifier shift
bspc config external_rules_command /home/amos/scripts/external_rules.sh

bspc rule -a "*" split_dir=east
bspc rule -a copyq state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Arandr sticky=on state=floating
bspc rule -a Deadbeef state=floating
bspc rule -a Zathura state=tiled
bspc rule -a netease-cloud-music desktop=o follow=on
bspc rule -a xfreerdp desktop=w follow=on
bspc rule -a Luakit desktop=f follow=on
bspc rule -a Skype desktop=o state=fullscreen

# stalonetray &
xsetroot -cursor_name left_ptr
startconky
setbg.sh

# Program Workspaces

# Floating
# for_window [class="Lxappearance"] floating enable
# for_window [class="dolphin"] floating enable
# for_window [class="Pcmanfm"] floating enable
# for_window [class="copyq"] floating enable
# for_window [class="GoldenDict"] floating enable
# for_window [class="Seahorse"] floating enable
# for_window [class="Pavucontrol"] floating enable
# for_window [class="Telegram"] floating enable
# for_window [class="Deadbeef"] floating enable
# for_window [class="Pinentry"] floating enable
# for_window [class="Zotero" title="Zotero Preferences"] floating enable
# for_window [class="Zotero" title="Advanced Search"] floating enable
# for_window [class="Zotero" title="Update"] floating enable
# for_window [class="Zotero" title="ZotFile Preferences"] floating enable
# for_window [class="Fcitx-config-gtk3"] floating enable
# for_window [class="Emacs" instance="org-capture"] exec "/home/amos/scripts/showorg.sh", floating enable
