#!/usr/bin/env bash

# if test -e "$BSPWM_STATE"
# 	bspc wm -l "$BSPWM_STATE"
# 	rm "$BSPWM_STATE"
# end

bspc monitor -d w e d f v n i o c h
if [ "$(hostname)" = "abt480" ]; then
    bspc monitor DP2 -r
else
    bspc monitor DP2-2 -r
fi

bspc desktop v --layout monocle

bspc config border_width 0
bspc config window_gap 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config swallow_first_click true
bspc config gapless_monocle false
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config pointer_modifier lock
# bspc config pointer_modifier control
# bspc config ignore_ewmh_fullscreen true # ignore application full screen request
# bspc config pointer_action3 move
# Action performed when pressing pointer_modifier + button<n>. Accept the following values: move, resize_side, resize_corner, focus, none.
bspc config external_rules_command /home/amos/scripts/external_rules.sh

bspc rule -a "*" split_dir=east
bspc rule -a copyq state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Arandr sticky=on state=floating
bspc rule -a Deadbeef state=floating
bspc rule -a Transmission-remote-gtk state=floating
bspc rule -a flameshot manage=off
bspc rule -a Zathura state=tiled
bspc rule -a netease-cloud-music desktop=o follow=on
bspc rule -a xfreerdp desktop=w follow=on state=tiled
bspc rule -a Luakit desktop=f follow=on
bspc rule -a Skype desktop=o state=fullscreen

xsetroot -cursor_name left_ptr
# ~/scripts/startconky
# ~/scripts/setbg.sh
feh --bg-scale ~/git/serverconfig/black.jpg

# Program Workspaces

# Floating
# for_window [class="Lxappearance"] floating enable
# for_window [class="dolphin"] floating enable
# for_window [class="Pcmanfm"] floating enable
# for_window [class="copyq"] floating enable
# for_window [class="GoldenDict"] floating enable
# for_window [class="Seahorse"] floating enable
# for_window [class="Pavucontrol"] floating enable
# for_window [class="Telegram"] floating enable
# for_window [class="Deadbeef"] floating enable
# for_window [class="Pinentry"] floating enable
# for_window [class="Zotero" title="Zotero Preferences"] floating enable
# for_window [class="Zotero" title="Advanced Search"] floating enable
# for_window [class="Zotero" title="Update"] floating enable
# for_window [class="Zotero" title="ZotFile Preferences"] floating enable
# for_window [class="Fcitx-config-gtk3"] floating enable
# for_window [class="Emacs" instance="org-capture"] exec "/home/amos/scripts/showorg.sh", floating enable

# This somehow can fix tray icon on HiDPI
# snixembed --fork

/home/amos/scripts/movehome

/home/amos/scripts/showstalonetray.sh 1

fish -c "dunst &> /tmp/dunst.log &"
fish -c "sxhkd &> /tmp/sxhkd.log &"
fish -c "copyq &> /tmp/copyq.log &"
# fish -c "runscrcpy  &> /dev/null &"
# fish -c "rungnirehtet &"
fish -c "udiskie &> /tmp/udiskie.log &"
fish -c "/home/amos/git/microsocks/microsocks -i 0.0.0.0 -p 8080 &> /tmp/microsocks.log &"
fish -c "libinput-gestures-setup start &> /tmp/gestures.log &"
fish -c "clipserver -S &"
fish -c "pass show v2raysocks | v2ray -c /dev/stdin &> /tmp/v2raysocks.log &"
fish -c "miniserve -i 127.0.0.1 -p 8099 /home/amos/git/serverconfig/amos.pac &"
# use to sync selection and clipboard. copyq sometimes fails to do that.
# fish -c "parcellite &> /tmp/parcellite.log &"
# fish -c "flameshot &> /tmp/flameshot.log &"
# fcitx
fish -c "fcitx5 -d"
# autocutsel -fork -selection PRIMARY
# autocutsel -fork -selection CLIPBOARD
fish -c "kitty &"
