#!/usr/bin/env bash

extension=/home/amos/git/serverconfig/chromium/external-links/extension
rofi_chrome_extension=/home/amos/git/rofi-chrome/extension
url=chrome-extension://aocepclkpgckjeikiphffdlileoaceec/bookmarks.html

if ! curl -fsS http://127.0.0.1:9222/json/version >/dev/null; then
    /usr/bin/chromium \
        --no-default-browser-check \
        --disable-extensions-except="$extension,$rofi_chrome_extension" \
        --load-extension="$extension,$rofi_chrome_extension" \
        --remote-debugging-port=9222 \
        --no-startup-window >/dev/null 2>&1 &
    for _ in {1..100}; do
        curl -fsS http://127.0.0.1:9222/json/version >/dev/null && break
        sleep 0.05
    done
fi

exec /usr/bin/chromium --app="$url"
