#!/usr/bin/env bash

mkdir -p release
pushd release
case "$1" in
    llvm)
        cmake ../llvm -G Ninja -DLLVM_TARGETS_TO_BUILD='X86' -DLLVM_CCACHE_BUILD=On -DLLVM_ENABLE_PROJECTS='clang;libcxx;libcxxabi;compiler-rt;lld' -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_LLVM_DYLIB=On -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=1' ../llvm
        ninja
        ;;
    ccls)
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DSYSTEM_CLANG=On -DUSE_SHARED_LLVM=On -DCMAKE_PREFIX_PATH="$HOME/git/llvm/release;$HOME/git/llvm/release/tools/clang;$HOME/git/llvm/llvm;$HOME/git/llvm/clang"
        ninja
        ;;
    rdp)
        cmake .. -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=On
        ninja
        ;;
    fish)
        cmake .. -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=On
        ninja
        ;;
    copyq)
        cmake .. -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=On
        ninja
        ;;
esac
popd
ln -sf release/compile_commands.json .
