#!/tmp/gentoo/miniconda3/bin/python

from pycookiecheat import chrome_cookies
import subprocess
import sys
import os
from shutil import copyfile

def main():
    if len(sys.argv) < 2:
        print("usage: curlc [url] <curl args...>")
        sys.exit(1)

    curlargs = sys.argv[1:]
    for arg in curlargs:
        if arg[0] != '-':
            url = arg
            break

    copyfile("/home/amos/.local/share/qutebrowser/webengine/Cookies", "/tmp/Cookies")
    chrome = chrome_cookies(url, cookie_file="/tmp/Cookies")

    cargs = []
    carg = "cookie: "
    for k, v in chrome.items():
        cargs.append(k + "=" + v)
    carg += "; ".join(cargs)

    args = ["curl", "-L", "-s", "-H", carg]
    args.extend(curlargs)

    subprocess.run(args)


if __name__ == '__main__':
    main()
