#!/usr/bin/env bash

export TMPDIR=/tmp/clangd
mkdir -p $TMPDIR
if [ -n "$GUI" ]; then
    exec /usr/bin/clangd "$@"
elif [ -z "$CLANGD" ]; then
    exec $HOME/toolchain/bin/clangd "$@"
else
    exec $CLANGD "$@"
fi
