#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
COLORS_FILE="$DIR/colors.txt"
selected="$(rofi -dmenu -i -markup-rows -p Colors <$COLORS_FILE)"
[[ -z $selected ]] && exit 1
inputstr "$(echo "$selected" | cut -d\' -f2)"
