#!/usr/bin/env bash

# if [[ -z "${ccls_include_dirs}" ]]; then
#     exec ~/git/ccls/build/release/bin/ccls --log-file=/tmp/cq.txt "$@"
# fi

# export CCLS_TRACEME=1
# export CCLS_CRASH_RECOVERY=0

cxx_flags="-O0"

for i in $ccls_cxx_flags; do
	cxx_flags="${cxx_flags}, $i"
done

for i in $ccls_include_dirs; do
	cxx_flags="${cxx_flags}, -I$i"
done

blacklist="/tmp"
for i in $ccls_blacklist; do
	blacklist="${blacklist}, $i"
done

suffix=$(basename "$(git rev-parse --show-toplevel)")
if [[ ! -z "$suffix" ]]; then
	suffix=-"$suffix"
fi

multi=0
# if [[ -z "$ccls_multi" ]]
# then
#     multi=0
# else
#     multi=1
# fi
init=$(jq -c -n --arg multi "$multi" --arg blacklist "$blacklist" --arg cxx_flags "$cxx_flags" '
{
  "highlight": { "largeFileSize": 131072 },
  "cacheFormat": "blob",
  "cacheDirectory": "/home/amos/.cache/.ccls_cached_index",
  "client": { "snippetSupport": true },
  "index": {
    "multiVersion": $multi,
    "trackDependency": 1,
    "comments": 0,
    "initialBlacklist": [$blacklist]
  },
  "workspaceSymbol": { "caseSensitivity": 0, "maxNum": 2000 },
  "diagnostics": { "onChange": 1000, "onOpen": 1000, "onSave": 1000 },
  "completion": {
    "detailedLabel": false,
    "include": {
        "whitelist": ["ccutils", "/usr/(local/)?include/(sys/)?[^/]+.h$"],
        "blacklist": [
          "(x86_64-redhat-linux|x86_64-pc-linux-gnu)/(32|bits|tr1|tr2|parallel|experimental|profile|ext|debug)/",
          "^/usr/(local/)?include/c++/[0-9.]+/(bits|tr1|tr2|parallel|experimental|profile|ext|debug)/",
          "^/usr/(local/)?include/c++/v1/",
          "^/usr/(local/)?include/(?!c++).+"
        ]
    }
  },
  "clang": {
    "resourceDir": "/home/amos/git/llvm/release/lib/clang/8.0.0",
    "pathMappings": [
      "/usr/local/bin/cc:/home/amos/git/llvm/release/bin/clang",
      "/usr/local/bin/c++:/home/amos/git/llvm/release/bin/clang++"
    ],
    "excludeArgs": ["-fno-tree-loop-distribute-patterns"],
    "extraArgs": [
      "-xobjective-c++-header",
      "-resource-dir=/home/amos/git/llvm/release/lib/clang/8.0.0",
      "-D__cpp_deduction_guides=0",
      "-Wno-macro-redefined",
      $cxx_flags
    ]
  }
}' | sed 's/"/\\"/g' )

exec ~/git/ccls/release/ccls --log-file=/tmp/cq.txt$suffix --init="\"$init\"" "$@"
