#!/usr/bin/env bash

dir=$(jump-top | fzf +m --reverse --cycle \
  --bind 'esc:abort,alt-enter:become(echo {q})')
if [ -n "$dir" ]; then
    dir=$(echo "$dir" | sed "s|^~|$HOME|")
    if [ ! -d "$dir" ]; then
        tmux display-message "Directory not found: $dir"
        exit 1
    fi
    cd "$dir" && jump chdir
    tmux new-window -c "$dir" crush
fi
