#!/usr/bin/env bash

while true; do
    dir=$(jump-top | fzf +m --reverse --cycle \
      --bind 'esc:abort,alt-enter:become(echo {q})')
    if [ -z "$dir" ]; then
        break
    fi
    dir=$(echo "$dir" | sed "s|^~|$HOME|")
    if [ ! -d "$dir" ]; then
        jump clean
        continue
    fi
    cd "$dir" && jump chdir
    tmux new-window -c "$dir" crush
    break
done
