#!/usr/bin/env bash

file=$(realpath "$1")
session=$(tmux display-message -p "#S")
if [[ $session = "gui" ]]
then
    emacspopup "(doom/sudo-find-file \"$file\")"
else
    EMACS="emacsclient -n -q -u -e"
    tmux switch-client -t emacs
    if [ -z "$2" ]
    then
        $EMACS "(progn (setq +amos-tmux-need-switch t) (+amos/workspace-new) (doom/sudo-find-file \"$file\"))"
    else
        $EMACS "(doom/sudo-find-file \"$file\")"
    fi
fi
