#!/usr/bin/env bash

file=$(realpath "$1")
session=$(tmux display-message -p "#S")
if [[ $session = "gui" ]]
then
    EMACS="emacsclient -s mu4e -n -q -u --display $DISPLAY -e"
    $EMACS "(progn (select-frame (make-frame '((name . \"popup\")))) (find-file \"$file\"))"
else
    EMACS="emacsclient -n -q -u -e"
    tmux switch-client -t emacs
    if [ -z "$2" ]
    then
        $EMACS "(progn (setq +amos-tmux-need-switch t) (+amos/workspace-new) (find-file \"$file\"))"
    else
        $EMACS "(find-file \"$file\")"
    fi
fi
