#!/usr/bin/env bash

exec vim "$@"

if [[ $session == "gui" ]]; then
    emacsclient -s mu4e -c --frame-parameters='(quote (name . "emacs-editor"))' -q -u --display $DISPLAY "$@"
else
    emacsclient -nw --frame-parameters='(quote (name . "emacs-editor"))' -q -u $@
fi
