#!/usr/bin/env bash

export TERM=xterm-tmux-24bits
if [[ $session == "gui" ]]; then
    emacsclient -s mu4e -c --frame-parameters='(quote (name . "emacs-editor"))' -q -u --display $DISPLAY "$@"
else
    emacsclient -nw --frame-parameters='(quote (name . "emacs-editor"))' -q -u $@
fi
