#!/usr/bin/env bash

id="$(xwininfo -name "popup" -int 2> /dev/null | perl -ne 'print /xwininfo: Window id: (.*) "popup"/g')"
EMACS="emacsclient -s mu4e -n -q -u --display $DISPLAY -e"
if [ -z "$id" ]
then
    $EMACS "(progn (select-frame (make-frame '((name . \"popup\")))) $*)"
else
    $EMACS "(progn (let ((frame (+amos-get-frame-by-name \"popup\"))) (select-frame frame)) $*)"
    showpopup.sh
fi
