#!/usr/bin/env bash

host=${1:-201.nobida.cn}
set -e
cd
rsync -aHSR $host:git/llvm-project/release/bin/clang-format $host:'/tmp/gentoo/home/amos/git/llvm-project/release/lib/clang/*/include' $host:/tmp/gentoo/home/amos/git/ccls/release/ccls .
