#!/usr/bin/env bash

host=${1:-201.nobida.cn}
set -e
cd
rsync -aHSR --rsync-path "cd /tmp/gentoo/home/amos && rsync" $host:git/llvm-project/release/bin/clang-format $host:'git/llvm-project/release/lib/clang/*/include' $host:git/ccls/release/ccls .
