#!/usr/bin/env bash

id=$(xdotool getmouselocation | awk -F "window:" '{print $2}')
class=$(xprop -id $id WM_CLASS | awk -F ", \"" '{print substr($2, 1, length($2)-1)}')
swipe3left() {
    case "$class" in
    Brave-browser)
        xdotool key --window $id alt+Left
        ;;
    qutebrowser)
        xdotool key --window $id alt+F9
        ;;
    llpp)
        # xdotool key --window $id alt+F6
        xdotool key --window $id ctrl+o
        ;;
    esac
}

swipe3right() {
    case "$class" in
    Brave-browser)
        xdotool key --window $id alt+Right
        ;;
    qutebrowser)
        xdotool key --window $id alt+F10
        ;;
    llpp)
        # xdotool key --window $id alt+F6
        xdotool key --window $id ctrl+i
        ;;
    esac
}

swipe3up() {
    case "$class" in
    Brave-browser)
        xdotool key --window $id Home
        ;;
    qutebrowser)
        # xdotool key --window $id alt+F6
        xdotool key --window $id alt+F8
        ;;
    llpp)
        # xdotool key --window $id alt+F6
        xdotool key --window $id g
        ;;
    esac
}

swipe3down() {
    case "$class" in
    Brave-browser)
        xdotool key --window $id End
        ;;
    qutebrowser)
        xdotool key --window $id alt+F7
        # xdotool key --window $id G
        ;;
    llpp)
        # xdotool key --window $id alt+F6
        xdotool key --window $id G
        ;;
    esac
}

swipe4left() {
    case "$class" in
    Brave-browser)
        xdotool key --window $id ctrl+shift+Tab
        ;;
    qutebrowser|jupyterlab|discord)
        xdotool key --window $id ctrl+comma
        ;;
    esac
}

swipe4right() {
    case "$class" in
    Brave-browser)
        xdotool key --window $id ctrl+Tab
        ;;
    qutebrowser|jupyterlab|discord)
        xdotool key --window $id ctrl+period
        ;;
    esac
}

swipe4up() {
    case "$class" in
    Brave-browser)
        xdotool key --window $id ctrl+shift+t
        ;;
    qutebrowser)
        xdotool key --window $id alt+F5
        ;;
    esac
}

swipe4down() {
    case "$class" in
    Brave-browser)
        xdotool key --window $id ctrl+w
        ;;
    qutebrowser)
        xdotool key --window $id alt+F4
        ;;
    esac
}

pinch_in() {
    case "$class" in
    qutebrowser)
        xdotool click --window $id 6
        ;;
    esac
}

pinch_out() {
    case "$class" in
    qutebrowser)
        xdotool click --window $id 7
        ;;
    esac
}

pinch_clockwise() {
    case "$class" in
    qutebrowser)
        xdotool key --window $id alt+F7
        ;;
    esac
}

pinch_anticlockwise() {
    case "$class" in
    qutebrowser)
        xdotool key --window $id alt+F6
        ;;
    esac
}

$1
