#!/usr/bin/env bash

{ echo "$(git config --get remote.pushdefault)/$(git branch --show-current)"; git for-each-ref --format='%(upstream:short)'; } |
    perl -MList::Util=uniq -ne 'if (/\//) { substr $_, rindex($_, "/"), 1, "~"; push @remote, $_;} END { print uniq @remote }'
