#!/usr/bin/env bash

{
    # do we need master be shown?
    r=$(git config --get remote.pushdefault)
    if [[ -n "$r" ]]; then
        echo "$r/$(git branch --show-current)"
    fi
    git for-each-ref --format='%(upstream:short)'
} |
    perl -MList::Util=uniq -ne 'if (/\//) { substr $_, rindex($_, "/"), 1, "~"; push @remote, $_;} END { print uniq @remote }'
