#!/usr/bin/env bash

pkill -f "kitty -o allow_remote_control=yes --listen-on unix:/tmp/kitty_sock -T local" || :

pgrep -u "$(id -u)" -f '[/]scripts/tstart.sh remote( |$)' | while read -r pid; do
    # shortcut: use sshd as the session boundary; switch to PID files if non-SSH transports are added.
    while parent_pid=$(ps -o ppid= -p "$pid" 2>/dev/null); do
        parent_pid=${parent_pid//[[:space:]]/}
        [[ -n $parent_pid ]] || break
        [[ $(ps -o comm= -p "$parent_pid" 2>/dev/null) == sshd ]] || {
            pid=$parent_pid
            continue
        }
        kill "$pid" 2>/dev/null || :
        break
    done
done
