#!/usr/bin/env bash

if [ "$#" -ne "1" ]; then
    echo ""
    echo -e "\033[01;32mLimit checker\033[00m"
    echo -e "\033[01;37mUsage:\033[01;33m $0 process_name\033[00m"
    echo ""
    exit 0
fi

return-limits(){
    for pid in $@; do
        if [ -z $@ ]; then
            echo "[no $process running]"
        else
            echo "[$process #$pid — limits]"
            cat /proc/$pid/limits
        fi
    done
}

return-limits $1
