#!/usr/bin/env bash

set -e
cd $HOME/git/bc

PIDFILE=blive.pid
if [ -e "${PIDFILE}" ]; then
    PID=$(cat ${PIDFILE})
    kill ${PID} || true
    rm -rf ${PIDFILE}
fi

bash -c "node index.js &> /dev/null &"
