#!/usr/bin/env bash

bspc desktop --focus f

N=$(realpath "$1" &>/dev/null)
if [ -e "$N" ]; then
	"$HOME"/scripts/vivaldi file://"$N" "$2"
elif [ -n "$*" ]; then
	"$HOME"/scripts/vivaldi "$@"
else
	"$HOME"/scripts/vivaldi ~/git/tilde/index.html
fi
