#!/usr/bin/env bash

# set -x

# exec 3>&1 4>&2
# trap 'exec 2>&4 1>&3' 0 1 2 3
# exec 1>/tmp/log 2>&1

# echo "$@" > /tmp/log

bspc desktop --focus f

if [ "$DISPLAY" != "" ]
then
    xhost +
fi

N=$(realpath "$1" &>/dev/null)
if [ -e "$N" ]; then
	"$HOME"/scripts/vivaldi file://"$N" "$2"
else
	"$HOME"/scripts/vivaldi "$@"
fi
