#!/usr/bin/env fish

set addr $argv
if not string match -q 'mailto:*' -- $addr
    set addr "mailto:"$addr
end

if mailto $addr
   i3-msg workspace ""
else
   notify-send -t "mail" "mu4e" "Bad url!"
end
