#!/usr/bin/env bash

if [[ `hostname` = "abt480" ]]
then
    xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1600x900 --pos 0x0 --brightness 1 --output DP2 --off;
    monitormove eDP1 DP2;
else
    xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1600x900 --pos 0x0 --brightness 1 --output DP1 --off --output DP2-1 --off --output DP2-2 --off --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off;
    monitormove eDP1 DP2-2;
fi
pkill conky;
startconky
