#!/usr/bin/env bash

onlyscreen() {
    target="$1"

    for out in $(xrandr | awk '/ connected/{print $1}'); do
        if [ "$out" != "$target" ]; then
            xrandr --output "$out" --off
        fi
    done

    xrandr --output "$target" --primary --mode 3840x2160 --pos 0x0 --rotate normal
}

case $(hostname) in
    abt480)
        onlyscreen eDP-1
        ;;
    abx1gen3)
        onlyscreen eDP-1-1
        ;;
    t450s)
        xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1600x900 --pos 0x0 --brightness 1 --output DP1 --off --output DP2-1 --off --output DP2-2 --off --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
        ./monitormove eDP1 DP2-2
        ;;
    qtw)
        xrandr --output HDMI-1 --primary --mode 3840x2160 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2 --off
        ;;
    *)
        ~/.screenlayout/inversed.sh
        ;;
esac
redshiftctl on
