#!/usr/bin/env bash

if [[ $(hostname) == abt480 ]]; then
    xrandr --output VIRTUAL1 --off --output eDP1 --off --output DP2 --primary --mode 1920x1080_60.00 --pos 0x0 --brightness 1
    # xrandr --output VIRTUAL1 --off --output eDP1 --off --output DP2 --primary --mode 1920x1080 --pos 0x0 --brightness 1
    monitormove DP2 eDP1
else
    xrandr --output VIRTUAL1 --off --output eDP1 --off --output DP1 --off --output DP2-1 --off --output DP2-2 --primary --mode 1920x1080_60.00 --pos 0x0 --brightness 1 --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
    monitormove DP2-2 eDP1
fi
pkill conky
startconky
