#!/usr/bin/env bash

onlyscreen() {
    target="$1"
    mode="$2"  # scale or noscale
    cmd="xrandr"

    for out in $(xrandr | awk '/ connected/{print $1}'); do
        if [ "$out" != "$target" ]; then
            cmd="$cmd --output $out --off"
        fi
    done

    if [ "$mode" = "scale" ]; then
        # 1080p + scale 2x2
        cmd="$cmd --output $target --primary --mode 1920x1080 --scale 2x2 --pos 0x0 --rotate normal"
    else
        cmd="$cmd --output $target --primary --mode 3840x2160 --pos 0x0 --rotate normal"
    fi

    eval "$cmd"
}

case $(hostname) in
    abt480)
        # xrandr --output eDP-1 --off --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output HDMI-2 --off --output DP-2-1 --off --output DP-2-2 --off --output DP-2-3 --primary --mode 1920x1080 --pos 0x0 --rotate normal
        # monitormove DP-2-3 eDP-1
        onlyscreen DP-1-3 noscale
        # monitormove DP-1-2 eDP-1
        # xrandr --output eDP-1 --off --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output DP-1-3 --off --output DP-1-2 --primary --mode 3840x2160 --pos 0x0 --rotate normal --output DP-1-1 --off --output HDMI-2 --off
        # monitormove DP-1-2 eDP-1
        ;;
    abx1gen3)
        onlyscreen HDMI-0
        ;;
    t450s)
        xrandr --output VIRTUAL1 --off --output eDP1 --off --output DP1 --off --output DP2-1 --off --output DP2-2 --primary --mode 1920x1080_60.00 --pos 0x0 --brightness 1 --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
        monitormove DP2-2 eDP1
        ;;
    qtw)
        onlyscreen DP-1
        ;;
    *)
        ~/.screenlayout/default.sh
        ;;
esac
redshiftctl on
