#!/usr/bin/env bash

case $(hostname) in
    abt480)
        xrandr --output eDP-1 --off --output DP-1 --off --output DP-2 --primary --mode 1920x1080 --pos 0x0 --brightness 1 --set "Broadcast RGB" "Full" --output HDMI-1 --off --output HDMI-2 --off
        monitormove DP-2 eDP-1
        ;;
    t450s)
        xrandr --output VIRTUAL1 --off --output eDP1 --off --output DP1 --off --output DP2-1 --off --output DP2-2 --primary --mode 1920x1080_60.00 --pos 0x0 --brightness 1 --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
        monitormove DP2-2 eDP1
        ;;
    dorm)
        ~/.screenlayout/default.sh
        ;;
esac
redshiftctl on
killall -SIGUSR1 conky
