#!/usr/bin/env bash

pkill feh

f=$(realpath "$1")

if [ -d "$f" ]; then
    cd "$f"
    perl -e 'use File::Find::Rule; @l = File::Find::Rule->file()->name( qr/\.(?:jpe?g|png)$/i )->in( (".") );  system("feh", "-g", "1280x800", @l);'
else
    cd "$(dirname "$f")"
    perl -e 'use List::Util qw(first); @l = grep /\.(?:jpe?g|png)$/i, <*>;; $n=@l; $i = first { $l[$_] =~ /\Q$ARGV[0]/ } 0..$#l; system("feh", "-g", "1280x800", @l[$i-$n..$i-1])' "$(basename "$f")"
fi
