#!/usr/bin/env bash

sudo pkill openconnect
sudo pkill core
sudo netctl stop-all
sudo ip r d default
sudo ip r f table cn
sudo netctl switch-to "$1"
if [ $? -ne 0 ]; then
    sudo systemctl stop zerotier-one
    sudo systemctl stop dnsmasq
    sleep 5
    sudo systemctl start zerotier-one
    sudo systemctl start dnsmasq
fi

# addroutes
