#!/usr/bin/env bash

sudo pkill openconnect
sudo pkill core
sudo ip l s enp0s20f0u4u1u2 down
sudo ip l s enp0s31f6 down
sudo ip l s wlp3s0 down
sudo netctl stop-all
sudo ip r d default
sudo ip r f table cn
sudo netctl switch-to "$1"
if [ $? -ne 0 ]; then
    sudo systemctl stop dnsmasq
    sleep 5
    sudo systemctl start dnsmasq
fi
