#!/usr/bin/env bash

case $(hostname) in
    abt480)
	# xrandr --output eDP-1 --off --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output HDMI-2 --off --output DP-2-1 --off --output DP-2-2 --off --output DP-2-3 --primary --mode 1920x1080 --pos 0x0 --rotate normal --brightness 1 --set "Broadcast RGB" "Full"
	xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output HDMI-2 --off --output DP-2-1 --off --output DP-2-2 --off --output DP-2-3 --off
        monitormove DP-2-3 eDP-1
        bspc monitor "HDMI-2" -d o2
        if arr=($(bspc query -D -m "" --names)); then
            for node in $(bspc query -N -d "$desktop"); do
                bspc node "$node" --to-desktop "$desktop"2
            done
        fi
if arr=($(bspc query -N -m "$2")); then
    for node in "${arr[@]}"; do
        bspc node "$node" --to-monitor "$1"
    done
fi
bspc monitor "$2" -r
bspc monitor "$1" -d w e d f v n i o p c h
bspc desktop --focus "$od"
bspc desktop v --layout monocle
setbg.sh

        ;;
    t450s)
        xrandr --output VIRTUAL1 --off --output eDP1 --off --output DP1 --off --output DP2-1 --off --output DP2-2 --primary --mode 1920x1080_60.00 --pos 0x0 --brightness 1 --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off
        monitormove DP2-2 eDP1
        ;;
    abbox)
        xrandr --output HDMI-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off
        monitormove HDMI-1 DP-1
        ;;
    *)
        ~/.screenlayout/default.sh
        ;;
esac
redshiftctl on
killall -SIGUSR1 conky
