#!/usr/bin/env fish

if test (count $argv) -ne 1
    echo "Usage: "(status filename)" <message>"
    exit 1
end
set max 74994
set str $argv[1]
set buf "notify-send OSC52Command '\n$str'"
set esc "\033]52;z;"(printf -- "%b" "$buf" | head -c $max | base64 | tr -d '\r\n')"\07"
set esc "\033Ptmux;\033"$esc"\033\\" # tmux
printf -- "%b" "$esc"
