#!/usr/bin/env fish

if test (count $argv) -ne 1
    echo "Usage: $_ <file>"
    exit 1
end
set max 74994
set file $argv[1]
if test -d $file -o -f $file
    if test (stat -c%s $file) -ge 30000000
        echo "File $file is too large."
        exit 1
    end
    set path (readlink -f $file)
    set buf "scp "(whoami)"@"(hostname)":"$path" "/tmp/(basename $path)
    set esc "\033]52;z;"(printf -- "%b" "$buf" | head -c $max | base64 | tr -d '\r\n')"\07"
    set esc "\033Ptmux;\033"$esc"\033\\" # tmux
    printf -- "%b" "$esc"
    osc52open "/tmp/"(basename $path)
else
    echo "File $file is not an existing file or directory."
    exit 1
end
