#!/usr/bin/env fish

if test (count $argv) -ne 1
    echo "Usage: $_ <file>"
    exit 1
end
set file $argv[1]
set addr (ztaddr)
set max 74994
set esc "\033]52;z;"(printf 'xdg-open '(realpath $file) | head -c $max | base64 | tr -d '\r\n')"\07"
set esc "\033Ptmux;\033"$esc"\033\\" # tmux
printf "$esc"
