#!/usr/bin/env bash

rm -rf * .*
../binutils-gdb/configure --prefix=/home/amos/gentoo/usr/local/ --disable-binutils --disable-gold --disable-ld --disable-gas --disable-gprof
bear make -j40
make install
