#!/usr/bin/env bash

root="$HOME/.password-store"

# get all password files and create an array
list_passwords() {
    cd "${root}" || exit
    pw_list=($(fd -E 'docker-credential-helpers' 'gpg$'))
    printf '%s\n' "${pw_list[@]%.gpg}" "otp" | sort -n
}

selected_password="$(list_passwords 2>/dev/null | rofi -steal-focus -dmenu -matching fuzzy -sort fzf -p "pass > ")"

rofi_exit=$?
if [[ $rofi_exit -eq 1 ]]; then
    exit
fi

if [[ "$selected_password" = "otp" ]]; then
    inputstr "$(pass show scripts/otp | bash)"
else
    inputstr "$(pass show "$selected_password")"
fi
