#!/usr/bin/env bash

# set -x

if [ -z "${ROFI_OUTSIDE}" ]; then
	rofi -modi "url:$0" -show url
	exit
fi

case $ROFI_RETV in
1)
	url=$ROFI_INFO
	luakit "$url" &>/dev/null
	;;
0)
	echo -en "\0markup-rows\x1ftrue\n"
	template=""
	while read -r name url
	do
		printf "    %s\0info\x1f%s\n" "$name" "$url"
	done < <(pass urls)
	;;
*)
	exit 0
	;;
esac
