#!/usr/bin/env bash

print_luakit_db() {
    sqlite3 "$1" 'select a.path from downloads a order by finish_time desc'
}

downloads() {
    print_luakit_db "$HOME/.local/share/luakit/downloads.db"
}

path="$(downloads | rofi -p 'luakit downloads > ' -dmenu)"
xdg-open "$path"
