#!/usr/bin/env zsh

set -e

root="$HOME/.docsets"

cd $root

docs=(*/)

case $1 in
    -s) search="$2"; shift; shift;;
esac;

doc=(${@:-$(printf '%s\n' "${docs[@]%.docset/}" | rofi -dmenu -i -p "Doc > ")})

db=($root/${^doc[@]}.docset/Contents/Resources/docSet.dsidx) # zsh feature

prefix=($root/${^doc[@]}.docset/Contents/Resources/Documents/) # zsh feature

sql="select name || '   ' || type || '   ' || '%s' || char(10) || '%s' || path from searchIndex"

if [ -n "$search" ]; then
    sql=$sql" where name like '%% $search %%' or name like '$search %%' or name like '%% $search' or name = '$search' collate nocase"
    # sql=$sql" where name = '$search' collate nocase"
fi

for i in {1..${#db[@]}}
do
    cmds=(${cmds[@]} ${(f)"$(printf "sqlite3 \"${db[$i]}\" \"$sql\"" ${@[$i]} ${prefix[$i]})"})
done

for cmd in ${cmds[@]}
do
    echo $cmd
    array=(${array[@]} ${(f)"$(eval $cmd)"})
done

declare -a items paths

for ((i = 1, j = 1, k = 2; k <= ${#array[@]}; ++i, j = 2 * i - 1, k = j + 1)); do
    items[$i]=${array[$j]}
    paths[$i]=${array[$k]}
done

idx=$(printf '%s\n' "${items[@]}" | rofi -dmenu -i -format 'd' -p "$* > ")

vivaldi file://${paths[$idx]}
