#!/usr/bin/env bash

# id="2717:ff48"
id="18d1:4ee7"
fuser -k /tmp/scrcpy.lock
pkill -f "$id"
cd /home/amos/git/scrcpy
exec {lockfd}>/tmp/scrcpy.lock && flock "$lockfd" || exit
while :; do adb wait-for-device && ./run release -x "$id"; sleep 0.2; done
