#!/usr/bin/env bash

maim -s | zbarimg -q --raw - | perl -ne 'use URI; use URL::Search qw( $URL_SEARCH_RE ); /($URL_SEARCH_RE)/ or die; my $url = URI->new($1); $url->scheme(lc $url->scheme); $url->host(lc $url->host); print $url->as_string' | xclip
