#!/usr/bin/env bash
set -euo pipefail

:set -u *://host/* content.headers.user_agent "Kim/0.9.9 integration Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Kim/0.9.9 Chrome/69.0.3497.128 Electron/4.2.6 Safari/537.36"
