#!/usr/bin/env fish

# exec {lockfd}>/tmp/emacs.lock && flock $lockfd || exit;
# exec emacsclient -a '' -t -c
# flock -nox /tmp/emacs.lock -c "emacsclient -a '' -t -c" || echo "unable to lock, perhaps files opened by emacs don't exit?"
exec emacsclient -a '' -t -c
