#!/usr/bin/env bash

export HTOP_SUSPEND=1
if echo 1 | socat - UNIX-CONNECT:/tmp/htop.dtach &> /dev/null; then
    exec dtach -a /tmp/htop.dtach -E -z
else
    exec dtach -A /tmp/htop.dtach -E -r ctrl_l -z htop
fi
