#!/usr/bin/env bash

function finish {
  tput cnorm
  kill -s SIGINT $PID
  wait $PID
  perf script -i $df | stackcollapse-perf.pl | grep -v cpu_idle | flamegraph.pl > $ds
  fish -c "osc52browser $ds"
  exit 0
}

trap finish INT

PREFIX=$1
shift
df=$1
shift
ds=$1
shift
nohup "$@" > /dev/null &
PID=$!
tput civis # hide cursor
DATE_FORMAT="+%H:%M:%S"
START_TIME=$(date +%s)
DATE_INPUT="now-${START_TIME}sec"
while true; do
    STOPWATCH=$(TZ=UTC date --date "$DATE_INPUT" $DATE_FORMAT)
    printf "\r\e%s%s\e[0m" "$PREFIX" "$STOPWATCH"
    sleep 0.2
done
