#!/bin/bash

source $HOME/.config/teiler/config

imageUpload () {
    upload "$1"
}

videoUpload () {
    cd "${vid_path}"
    upload "${1}"
}

clipUpload () {
    cd "${paste_path}"
    upload "${1}"
}

if [[ $1 == "--upload" ]]; then
    files=$(echo "$@" | cut -d ' ' -f3-)
    if [[ $2 == "image" ]]; then imageUpload "${files}"
    elif [[ $2 == "video" ]]; then videoUpload "${files}"
    elif [[ $2 == "text" ]]; then clipUpload "${files}"
    fi
fi
