#!/usr/bin/env bash

tldr -l | sed 's/, /\n/g' | sed '/^$/d' | fzf -e --preview 'tldr {}' --preview-window=up:60% --bind=ctrl-o:kill-line,enter:ignore,ctrl-g:unix-line-discard,ctrl-q:unix-line-discard,esc:unix-line-discard
