#!/usr/bin/env bash

usage () {
    echo "Usage: $0 pid1 [pid2]"
    exit 1
}

if [[ "$#" -ne 2 && "$#" -ne 1 ]]; then
    usage
fi

re='^[0-9]+$'
if ! [[ $1 =~ $re ]]; then
    kill -0 $1 &> /dev/null || usage
fi

if [[ "$#" -eq 2 ]]; then
    [[ $2 =~ $re ]] && kill -0 $2 &> /dev/null || usage
fi

tmux neww -a -n PerfTopDiff "sleep 1; perf top -p $1"

if [[ "$#" -eq 2 ]]; then
    tmux splitw -h "perf top -p $2"
fi
