#!/usr/bin/env bash

if [ Debug = "$(tmux display-message -p '#W')" ]; then
    :
    # ttys=$(tmux list-panes -F "#{pane_tty}")
    # for tty in ${ttys[@]}
    # do
    #     echo "fuser -s -k -9 $tty" >> /tmp/ll
    #     fuser -s -k -9 $tty
    # done
else
    current_panes=$(tmux list-panes -F "#{pane_id}")
    SAVEIFS="$IFS"
    IFS=$'\n'
    array=($current_panes)
    # Restore IFS
    IFS=$SAVEIFS
    for ((i = 0; i < ${#array[@]}; i++)); do
        tmux send-keys -t "${array[$i]}" C-c C-c
    done
fi
tmux kill-window
