#!/usr/bin/env bash

window=""
if [ -n "$1" ]
then
   window="-t $1"
fi

if [ Debug = "$(tmux display-message -p '#W')" ]; then
    :
    # ttys=$(tmux list-panes -F "#{pane_tty}")
    # for tty in ${ttys[@]}
    # do
    #     echo "fuser -s -k -9 $tty" >> /tmp/ll
    #     fuser -s -k -9 $tty
    # done
else
    current_panes=$(tmux list-panes $window -F "#{pane_tty}" | sed "s=/dev/==")
    SAVEIFS="$IFS"
    IFS=$'\n'
    array=($current_panes)
    # Restore IFS
    IFS=$SAVEIFS
    for ((i = 0; i < ${#array[@]}; i++)); do
        kill -9 $(pgrep -t${array[$i]})
    done
fi
tmux kill-window $window
