#!/usr/bin/env bash

if [ "$1" = "-p" ]; then
    tmux neww -a -n Debug-"$2" "sleep infinity"
else
    tmux neww -a -n Debug "sleep infinity"
fi
tmux set -w pane-border-status off
tmux splitw -h bash
tmux select-pane -t 1
tty1=$(tmux display -p "#{pane_tty}")

tmux splitw -v bash
tty4=$(tmux display -p "#{pane_tty}")
tmux select-pane -t 1

tmux splitw -v "sleep infinity"
tty2=$(tmux display -p "#{pane_tty}")

# tmux splitw -h "sleep infinity"
# tty3=$(tmux display -p "#{pane_tty}")

# tmux list-windows
# tmux select-layout "328c,211x50,0,0{105x50,0,0[105x18,0,0,337,105x18,0,19{52x18,0,19,340,52x18,53,19,341},105x12,0,38,339],105x50,106,0,338}"

tmux select-pane -t 3
if [ "$1" = "-p" ]; then
    tmux send-keys "reptyr -l sh -c 'tmux select-pane -t 4; tmux send-keys \"cgdb -- -q -tty \$REPTYR_PTY -ex \\\"dashboard threads -output $tty1\\\" -ex \\\"dashboard stack -output $tty2\\\" -ex \\\"attach $2 &\\\" \" C-m'" C-m
else
    if [ -f "$1" ]
    then
       program=$1
    else
       program=$(which "$1")
    fi
    shift
    tmpfile=$(mktemp /tmp/tmuxgdb-wrapper.XXXXXX)
    export >> $tmpfile
    tmux send-keys "reptyr -l sh -c 'tmux select-pane -t 4; tmux send-keys \"source $tmpfile; rm $tmpfile\" C-m; tmux send-keys \"cgdb -- -q -ex \\\"file $program\\\" -tty \$REPTYR_PTY -ex \\\"dashboard threads -output $tty1\\\" -ex \\\"dashboard stack -output $tty2\\\" -ex \\\"start '\"${*@Q}\"'\\\" $program\"  C-m'" C-m
fi
sleep 0.2
tmux send -R -t 3
