#!/usr/bin/env bash

while IFS= read -r line; do
    echo $line
    case $line in
        *bluetooth*)
            echo 15 | sudo tee $line
            ;;
        *serio2*)
            echo 255 | sudo tee $line
            ;;
    esac
done < <(/usr/bin/fd sensitivity /sys)
