#!/usr/bin/env bash

# if pgrep -f 'kytan'
# then
#     sudo pkill kytan
# #    sudo sed -e 's/.*8.8/#\0/ ; s/#\(.*223\)/\1/' -i /etc/resolv.conf
# #    sudo sed -e 's/precedence ::ffff:0:0\/96  100/#\0/' -i /etc/gai.conf
# else
#     sudo RUST_LOG=DEBUG RUST_BACKTRACE=1 kytan -m c -h la.wentropy.com -p 8555 -s c3d62f381cc229de5c69ea7fec7faffce8d8da90307c1f9a8b1e7008b402be7c &
#     # sudo RUST_LOG=DEBUG RUST_BACKTRACE=1 kytan -m c -h 2604:180:3:f9e::59d3 -p 8555 -s c3d62f381cc229de5c69ea7fec7faffce8d8da90307c1f9a8b1e7008b402be7c &
#     #sudo kytan -m c -h 2604:180:3:f9e::59d3 -p 8555 -s c3d62f381cc229de5c69ea7fec7faffce8d8da90307c1f9a8b1e7008b402be7c &
# #    sudo sed -e 's/.*223/#\0/ ; s/#\(.*8.8\)/\1/' -i /etc/resolv.conf
# #    sudo sed -e 's/#\(precedence ::ffff:0:0\/96  100\)/\1/' -i /etc/gai.conf
# fi
# sleep 0.5
# pkill -SIGRTMIN+11 i3blocks

(( UID == 0 )) || exec sudo "$0" "$@" || exit

ip r a 10.0.0.0/8 via 10.61.2.254
if ip r | grep -q '128.0.0.0/1'
then
    ip r d 0.0.0.0/1
    ip r d 128.0.0.0/1
else
    ip r a 0.0.0.0/1 via 172.26.133.192
    ip r a 128.0.0.0/1 via 172.26.133.192
fi
pkill -SIGRTMIN+11 i3blocks
