#!/usr/bin/env bash

die() { echo "$*" 1>&2 ; exit 1; }

cd ~/.emacs.d || die "cd failed"
rm ./*.elc
find {core,modules} -iname '*.elc' -delete
git pull
set -e
bin/doom -y update
bin/doom -y refresh
bin/doom -y compile
