#!/usr/bin/env bash

curl -s https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt | sudo tee /etc/.hostnames.txt > /dev/null
curl -s https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt | sudo tee /etc/.domains.txt > /dev/null

{
	echo '
port=53
no-resolv
no-poll
min-cache-ttl=3600
conf-file=/etc/.domains.txt
addn-hosts=/etc/.hostnames.txt
#server=127.0.0.1#5300
server=8.8.8.8
server=/ict.ac.cn/159.226.8.6
ipset=/ieee.org/gfwlist
ipset=/acm.org/gfwlist
ipset=/sciencedirect.com/gfwlist
ipset=/cn/gfwlist
'
	curl -s https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
} | sudo tee /etc/dnsmasq.conf >/dev/null

sudo systemctl restart dnsmasq

notify-send -a "Dnsmasq" "Dnsmasq Updated"
