#!/usr/bin/env bash

{
	echo '
port=53
no-resolv
no-poll
min-cache-ttl=3600
server=127.0.0.1#5353
server=/163.com/202.38.64.1
server=/126.net/202.38.64.1
server=/ict.ac.cn/159.226.8.6
'
	curl -s https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
} | sudo tee /etc/dnsmasq.conf >/dev/null

sudo systemctl restart dnsmasq
