#!/usr/bin/env bash

#!/usr/bin/env bash

errlog() {
    notify-send -a "teiler" "Error Log" "$(cat /dev/fd/2)"
    exit 1
}
set -o pipefail

(curl -u "$(awk '{$1=$1};1' ~/.userpass)" -F c=@"$1" "https://la.wentropy.com/?u=1" 2>/dev/null | perl -pe 'chomp if eof; $_.=".png"' | copyq add - && copyq select 0) || errlog
notify-send -a "teiler" "Text Uploaded" "$(copyq clipboard)"
