#!/usr/bin/env bash

errlog() {
    notify-send -a "teiler" "Error Log" "$(cat /dev/fd/2)"
    exit 1
}
set -o pipefail

if [[ -z $2 ]]; then
    # suffix=${1##*.}
    # if [[ $suffix == "jpg" || $suffix == "jpeg" || $suffix == "png" ]]; then
    #     if [[ -z $GUI ]]; then
    #         curl -u "$(awk '{$1=$1};1' ~/.userpass)" -F c=@"$1" "https://la.wentropy.com/?u=1" 2>/dev/null | env s="$suffix" perl -pe 'chomp if eof; $_.=$ENV{s}' | osc52clip
    #     else
    #         (curl -u "$(awk '{$1=$1};1' ~/.userpass)" -F c=@"$1" "https://la.wentropy.com/?u=1" 2>/dev/null | env s="$suffix" perl -pe 'chomp if eof; $_.=$ENV{s}' | copyq add - && copyq select 0) || errlog
    #         notify-send -a "teiler" "Image Uploaded" "$(copyq clipboard)"
    #     fi
    # else
    if [[ -z $GUI ]]; then
        curl -u "$(awk '{$1=$1};1' ~/.userpass)" -F c=@"$1" "https://la.wentropy.com/?u=1" 2>/dev/null | perl -pe 'chomp if eof' | osc52clip
    else
        (curl -u "$(awk '{$1=$1};1' ~/.userpass)" -F c=@"$1" "https://la.wentropy.com/?u=1" 2>/dev/null | perl -pe 'chomp if eof' | copyq add - && copyq select 0) || errlog
        notify-send -a "teiler" "Text Uploaded" "$(copyq clipboard)"
    fi
    # fi
else
    curl -u "$(awk '{$1=$1};1' ~/.userpass)" -F c=@"$1" "https://la.wentropy.com/?u=1" 2>/dev/null
fi
