#!/usr/bin/env bash

errlog() {
    notify-send -a "teiler" "Error Log" "$(cat /dev/fd/2)"
    exit 1
}
set -o pipefail

(curl -u "$(pass show misc/pastebin)" -F 'paste=<'"$1" la.wentropy.com 2>/dev/null | perl -pe 'chomp if eof' | copyq add - && copyq select 0) || errlog
notify-send -a "teiler" "Text Uploaded" "$(copyq clipboard)"
