#!/usr/bin/env perl

use Clipboard;
use IPC::Run3;
my $engine = $ARGV[0];
my $url    = Clipboard->paste;
$url =~ s/^\s+|\s+$//g;
unless ( $url =~ /^https?:\/\// ) {
    $url =~ s/([^A-Za-z0-9])/sprintf("%%%02X", ord($1))/seg;
    $url = "$engine$url";
}
run3 [ 'luakit', $url ];
