#!/usr/bin/env perl

use strict;
use warnings;
use IPC::Run3;

my $engine = $ARGV[0];
my $url;

run3 ['xclip', '-selection', 'clipboard', '-o'], \undef, \$url, \undef;
$url =~ s/^\s+|\s+$//g;
unless ( $url =~ /^https?:\/\// ) {
    $url =~ s/([^A-Za-z0-9])/sprintf("%%%02X", ord($1))/seg;
    $url = "$engine$url";
}
run3 [ 'luakit', $url ];
