#!/usr/bin/env bash

# flashso="/usr/lib/PepperFlash/libpepflashplayer.so"
# flashversion=`strings $flashso 2> /dev/null | grep LNX | cut -d ' ' -f 2 | sed -e "s/,/./g"`
# vivaldi-snapshot --ppapi-flash-path=$flashso --ppapi-flash-version="$flashversion" --proxy-pac-url="file:///home/amos/dotfiles/pac.js" --user-data-dir=/home/amos/.config/vivaldi "$@"

# /home/amos/softwares/qt59env/bin/python -m qutebrowser --backend webengine "$@"

# if [ "$#" -ge 2 ]
# then
#     luakit "$2"
# elif [ "$#" -ge 1 ]
# then
#     luakit "$1"
# else
#     luakit
# fi
# exit 0

exists() { [[ -e $1 ]]; }; shopt -s nullglob
if ! exists /run/user/1000/qutebrowser/*
then
    qutebrowser ~/git/serverconfig/dumb.html &
    while read -r && [[ $REPLY != *ATTRIB\ ipc-* ]]; do :; done < <(inotifywait -m /run/user/1000/qutebrowser)
fi
socket=(/run/user/1000/qutebrowser/*)
workspace=$(i3-msg -t get_workspaces | jq -r 'map(select(.focused))[0].name')
if i3-msg -t get_tree | jq -r --arg v "$workspace" '.nodes[].nodes[].nodes[] | .type == "workspace" and .name == $v and (.nodes[].window_properties.class=="qutebrowser" or .nodes[].nodes[].window_properties.class=="qutebrowser")' | grep true
then
    i3-msg focus right > /dev/null
    ruby -r json -e 'printf "{\"args\":%s, \"target_arg\":\"last-focused\", \"protocol_version\":1}\n", JSON.generate(ARGV)' -- "$@" | socat - UNIX-CONNECT:"${socket[0]}" && exit 0
else
    ruby -r json -e 'printf "{\"args\":%s, \"target_arg\":\"window\", \"protocol_version\":1}\n", JSON.generate(ARGV)' -- "$@" | socat - UNIX-CONNECT:"${socket[0]}" && exit 0
fi
