#!/usr/bin/env bash

# termite -e weechat -t weechat

# termite -t weechat -e "ssh -t 172.24.88.1 tmux -u new-session -A -s weechat"
termite -t weechat -e "ssh -t 172.24.88.1 'env -i HOME=\$HOME TERM=\$TERM USER=\$USER SSH_CONNECTION=\"\$SSH_CONNECTION\" /home/amos/gentoo/startprefix'"

