#!/usr/bin/env bash

# /sound /audio-mode:0  #client
# /sound /audio-mode:1  #server
# /audio-mode:2  #disable

if sudo virsh list | grep -q win10; then
    xfreerdp +aero +menu-anims +window-drag /rfx /gfx /sound:sys:pulse /microphone /size:$(xrandr | head -n1 | cut -d, -f2 | cut -d" " -f3-5 | sed 's/ //g') +auto-reconnect /dynamic-resolution /bpp:32 +home-drive -toggle-fullscreen +fonts -grab-keyboard /u:amos /p:$(pass show misc/ztq) /v:192.168.122.109:3389
else
    xfreerdp +aero +menu-anims +window-drag /rfx /gfx /audio-mode:2 /size:$(xrandr | head -n1 | cut -d, -f2 | cut -d" " -f3-5 | sed 's/ //g') +auto-reconnect /dynamic-resolution /bpp:32 +home-drive -toggle-fullscreen +fonts -grab-keyboard /u:amos /p:$(pass show misc/ztq) /v:172.26.178.148:3389
fi
