#!/usr/bin/env bash


xfreerdp -wallpaper /rfx /gfx:avc444 /audio-mode:2 /size:$(xrandr | head -n1 | cut -d, -f2 | cut -d" " -f3-5 | sed 's/ //g') +auto-reconnect /dynamic-resolution /bpp:16 +home-drive -toggle-fullscreen +fonts -grab-keyboard /u:Administrator /p:$(gpg -d ~/passwords/win.gpg) /v:10.61.3.88:3389
