#!/usr/bin/env bash

xfreerdp +aero +menu-anims +window-drag /rfx /gfx:avc444 /audio-mode:2 /size:$(xrandr | head -n1 | cut -d, -f2 | cut -d" " -f3-5 | sed 's/ //g') +auto-reconnect /dynamic-resolution /bpp:32 +home-drive -toggle-fullscreen +fonts -grab-keyboard /u:Administrator /p:$(gpg -d ~/passwords/Ztq.gpg) /v:172.24.10.1:3389
