#!/usr/bin/env bash

xfreerdp +aero +menu-anims +window-drag /rfx /gfx /audio-mode:2 /size:$(xrandr | head -n1 | cut -d, -f2 | cut -d" " -f3-5 | sed 's/ //g') +auto-reconnect /dynamic-resolution /bpp:32 +home-drive -toggle-fullscreen +fonts -grab-keyboard /u:amosbird@gmail.com /p:$(pass show misc/Ztq) /v:172.26.178.148:3389
