#!/usr/bin/env bash

# bash logging
# set -x
# exec 3>&1 4>&2
# trap 'exec 2>&4 1>&3' 0 1 2 3
# exec 1>>/tmp/winstart.log 2>&1

if ! pgrep freerdp >/dev/null; then
    winremote &
fi

qq='"C:\Program Files (x86)\Tencent\TIM\Bin\Timwp.exe"'
ww='"C:\Program Files (x86)\AliWangWang\9.12.10C\WWCmd.exe"'

case "$1" in
qq)
    cmd=$qq
    ;;
ww)
    cmd=$ww
    ;;
*)
    echo error
    exit 1
    ;;
esac

url=${2//&/^&}

cmd=("$cmd" "$url")

if sudo virsh list | grep -q win10; then
    echo -n "${cmd[@]}" >/dev/udp/192.168.122.109/11000
else
    echo -n "${cmd[@]}" >/dev/udp/172.26.178.148/11000
fi

bspc desktop --focus w
