#!/usr/bin/env bash

ifconfig | perl -e '
$this_line = "";
while(<>) {
    $last_line = $this_line;
    $this_line = $_;
    if ($last_line =~ /^ztppi3wb3p/) {
        print $this_line =~ /inet (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/g;
        exit 0;
    }
}
exit 1;
' || echo -n 127.0.0.1
