#!/usr/bin/env bash

ifconfig | perl -e '
$this_line = "";
while(<>) {
    $last_line = $this_line;
    $this_line = $_;
    if ($last_line =~ /^zt/) {
        print $this_line =~ /inet (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/g;
        exit;
    }
}
'
