#!/usr/bin/env bash

echo "

Output :
---------------------------------------------------"

case "$1" in
debug)
    tmux switch-client -t amos
    tmux run -t amos "fish -c 'tmuxgdb deb'"
    ;;
debug_test)
    tmux switch-client -t amos
    tmux run -t amos "fish -c 'tmuxgdb deb_test'"
    ;;
bench)
    env LD_PRELOAD="$cc_ld_preload" LD_LIBRARY_PATH="$cc_ld_library_path" ./bench --benchmark_color=false
    ;;
test)
    env LD_PRELOAD="$cc_ld_preload" LD_LIBRARY_PATH="$cc_ld_library_path" ./rel_test
    ;;
*)
    env LD_PRELOAD="$cc_ld_preload" LD_LIBRARY_PATH="$cc_ld_library_path" ./rel
    # ./rel
    ;;
esac
