#!/usr/bin/env bash

if [ "$*" = "route add default via 192.168.255.1 dev tun0" ]; then
    /usr/bin/ip route add default via 192.168.255.1 dev tun0 table ioa2
    /usr/bin/ip route add default via 192.168.255.1 dev tun0 table ioa metric 101
    exit 0
fi

exec /usr/bin/ip "$@"
