[tools]
direnv = "latest"
eza = "latest"
ripgrep = "latest"
fd = "latest"
fzf = "latest"
k6 = "latest"
shfmt = "latest"
"github:gsamokovarov/jump" = "latest"
"github:docker/docker-credential-helpers" = { version = "latest", matching = "docker-credential-pass", bin = "docker-credential-pass" }
atuin = "latest"
"github:fish-shell/fish-shell" = { version = "latest", exe = "fish" }
"github:kovidgoyal/kitty" = { version = "latest", matching = "kitten-", bin = "kitten" }
sqlc = "latest"
"github:amosbird/clipserver" = "latest"
zig = "latest"
"github:upx/upx" = "latest"
micromamba = "latest"
gopass = "latest"
gh = "latest"

[settings]
experimental = true
