[tools]
direnv = "latest"
eza = "latest"
ripgrep = "latest"
fd = "latest"
fzf = "latest"
k6 = "latest"
shfmt = "latest"
"ubi:gsamokovarov/jump" = "latest"
"ubi:docker/docker-credential-helpers" = { version = "latest", exe = "docker-credential-pass" }
atuin = "latest"
"ubi:fish-shell/fish-shell" = "latest"
sqlc = "latest"

[settings]
experimental = true
