[tools]
direnv = "latest"
eza = "latest"
ripgrep = "latest"
fd = "latest"
fzf = "latest"
k6 = "latest"
shfmt = "latest"
"github:gsamokovarov/jump" = "latest"
"github:docker/docker-credential-helpers" = { version = "latest", exe = "docker-credential-pass" }
atuin = "latest"
"github:fish-shell/fish-shell" = { version = "latest", exe = "fish" }
sqlc = "latest"
"github:amosbird/clipserver" = "latest"

[settings]
experimental = true
